hackworthltd/hacknix

- overlays/patches.nix
Thanks to Holo-Host:
https://github.com/Holo-Host/holo-nixpkgs/blob/00da3ac8e1e0dfe900df4a88eb0bced556abe525/overlays/holo-nixpkgs/hydra/secure-github.diff
> Add a patch to make Hydra's GitHub token handling more secure.

- default.nix
- overlays/haskell-packages.nix
- release.nix
It's been broken upstream for weeks.
> Remove cabal-fmt.

- lib/default.nix
- nix/sources.json
See https://github.com/NixOS/nixpkgs/pull/88607.
> Switch to nixpkgs until udev fix is in nixpkgs-unstable.

- overlays/custom-packages.nix
It's based on 5.7-rc6, and according to the OpenWRT forums, the
5.7-rc3 mac80211 driver seems to have fixed the official ath10k
firmware issues.
> Switch linux_ath10k to use linux_testing.

- default.nix
- overlays/overrides.nix
- pkgs/vscode-python/default.nix
- pkgs/vscode/generic.nix
- pkgs/vscode/vscode.nix
- pkgs/vscode/with-extensions.nix
- release.nix
This override works on macOS.
Note, however, that the Python plugin is broken, as it requires a
writable extensions directory.
> Override vscode.

- .github/workflows/ci.yaml
Note that there are a few macOS packages that don't build at the moment, so the action currently fails, but the action bit is working, anyway.
> Run GitHub Actions on macOS.

- .github/workflows/ci.yaml
This will allow the action to make as much forward progress as
possible in the event of failed builds. It's useful because the
start-up time of Nix CI jobs on public GitHub builders is pretty
expensive.
> Add --keep-going to GitHub action.

- default.nix
- nix/default.nix
- nix/sources.json
- overlays/custom-packages.nix
- overlays/lib/hacknix.nix
- overlays/nixops-examples.nix
- overlays/nixops/logical.nix
- overlays/nixops/physical.nix
The example NixOps network lets us test our modules etc on Hydra.
> Switch back to upstream NixOps and add an example NixOps network.

- .github/workflows/bump-deps.yaml
For some unknown reason, sometime in the last few days, running niv on
a GitHub Actions runner requires a GITHUB_TOKEN. Rather than using a
personal access token from my account or the Hackworth Ltd bot's
account, we use the tibdex/github-app-token action to create a
one-time-use token.
> Fix niv update GitHub Action.

- flake.lock
- flake.nix
We flatten it and include all the overlay dependencies, as well. This
is much easier to deal with downstream.
> Refactor overlay.

- flake.nix
Python 3.8.7 was finally merged, so hopefully this fixes all remaining
Big Sur issues and we can deprecate our fork.
(Note that Python 3.8.7 isn't on nixpkgs-unstable yet, so we're using
the upstream trunk here until nixpkgs-unstable catches up.)
> Switch nixpkgs to upstream.

- flake.lock
- flake.nix
Upstream nixpkgs-unstable now works with Big Sur.
> Switch back to nixpkgs-unstable.

- nix/overlays/100-hydra.nix
- nix/patches/hydra/ignore-submodule-failures.patch
We have some git repos with private submodules. These submodules
contain secrets for deployment, but aren't needed by the Hydra in
order to evaluate the project and build its derivations.
The included patch will print a warning when submodules can't be
fetched, but the Hydra will keep going anyway.
> Patch Hydra so that it ignores git submodule failures.

- nix/overlays/100-nix.nix
- nix/patches/nix/etag.patch
See:
https://github.com/NixOS/nix/issues/4469
Here, rather than asserting when this condition occurs, we simply
output a warning, and provide the URL that generated the problem and
the expected/actual etags.
> Attempt to work around a recent Nix etags issue we're having.

- flake.lock
- flake.nix
This should prevent downstream users of this flake from needing to
specify the hydra nixpkgs input pin.
> Bump dependencies and fix Hydra nixpkgs input.

- nix/modules/networking/virtual-ips/default.nix
Previously this hasn't been necessary, but it appears that, if
enabling virtual IPs on a system where the default was to set `useDHCP
= true` on all interfaces, then the virtual-ip service will time out
waiting for a DHCP response that will never come!
> virtual-ips: set useDHCP to false.

- flake.lock
- flake.nix
- nix/overlays/100-aws.nix
- nix/pkgs/awscli2/default.nix
- nix/pkgs/chamber/default.nix
This version of the AWS Go SDK includes support for SSO, so we
shouldn't need aws-sso-credential-process anymore.
Also drop our old version of awscli2 as upstream now has a more recent
one.
> Update chamber to use most recent AWS Go SDK.

- examples/nix-darwin/build-host.nix
- examples/nix-darwin/remote-builder.nix
- flake.lock
- flake.nix
Note: the new nix-darwin used here allows us to specify the
darwinSystem system type at build time.
> Bump dependencies.

- flake.lock
- flake.nix
- nix/modules/dns/unbound-multi-instance/default.nix
- nix/modules/email/null-client/default.nix
- nix/modules/email/postfix-mta/default.nix
- nix/modules/email/relay-host/default.nix
Nix is majorly broken since
https://github.com/NixOS/nixpkgs/commit/946cc38f70a7dbea5d2c4bbeb4021b43beb3b3ce
Hopefully this is fixed by
https://github.com/NixOS/nixpkgs/commit/5e7e70b2004f58d852730c91ad9b0a0833d902f1
but until that's in nixpkgs-unstable, we'll revert to the last
nixpkgs-unstable before the breaking change.
> Revert nixpkgs version to fix a Nix issue.

- flake.lock
- nix/modules/config/remote-builds/remote-build-host/default.nix
Upstream nixpkgs now shows this warning:
```
Failed assertions:
- users.users.remote-builder.group is unset. This used to default to
nogroup, but this is unsafe. For example you can create a group
for this user with:
users.users.remote-builder.group = "remote-builder";
users.groups.remote-builder = {};
```
> Bump dependencies & assign remote-builder user to its own group.

- flake.nix
- nix/overlays/140-nix.nix
- nix/patches/nix/unset-is-macho.patch
See:
https://github.com/NixOS/nixpkgs/pull/138186
> nixUnstable: workaround macOS breakage until upstream fix is merged.

- flake.lock
- flake.nix
- nix/darwinModules/config/defaults/default.nix
Also, remove the workaround for
https://github.com/LnL7/nix-darwin/issues/373 as our nix-darwin fork
now has a patch for it (see
https://github.com/LnL7/nix-darwin/pull/379).
Note that this nix-darwin rev also removes the `nixUnstable` hacks we
were using previously so that we could use `nixStable` as the system
version, but `nixUnstable` for flakes support in the user's
environment and for `darwin-rebuild`. `nixStable` is now 2.4, so it
should be safe to use it for all scenarios we want to support.
> chore(nix): Bump dependencies.

- examples/nixos/build-host.nix
- flake.nix
- nix/common/config/services/vault/agent/template/github-credentials/default.nix
This uses the Vault plugin
https://github.com/martinbaillie/vault-plugin-secrets-github to
configure per-user, ephemeral, rotated HTTPS secrets.
> Add per-user Vault Agent git-credentials support.

- nix/modules/dns/unbound-multi-instance/default.nix
In case you want to render docs, the string becomes the example, verbatim.
Not sure what happens if you don't put a string there.
Found while debugging a large derivations bug in Nix.
> unbound-multi-insance: Quote literalExpression

- examples/nix-darwin/build-host.nix
- examples/nixos/build-host.nix
- nix/common/config/services/vault/agent/template/netrc/default.nix
We've been using this Vault Agent template for Cachix, and it has
worked fine until recently, when we started having issues using a
private Cachix cache. The issue appears to be related to
https://github.com/cachix/cachix/issues/406
which is worked around by adding a nonce login name. Furthermore, it's
likely that other netrc clients will need the login, so we now require
it.
> fix: Add a `login` to netrc credentials.

- .buildkite/pipeline.yaml
All our patches are now upstream.
> ci: switch to circuithub/nix-buildkite.

- flake.lock
- flake.nix
We're temporarily bumping to `nixpkgs` main branch to get the `openssl-3.0.7` fix, which is not yet included in `nixpkgs-unstable`.
> chore(nix): Bump dependencies for `openssl-3.0.7` fix.

- flake.nix
- nix/overlays/200-lima.nix
- nix/pkgs/lima/binary.nix
nixpkgs can't produce a VZ-capable lima binary at the moment, so when we want that, we can use this new `lima-binary` package in place of `lima`.
> feat: Add a `lima-binary` package.

- examples/nixos/build-host.nix
- examples/nixos/remote-build-host.nix
- flake.lock
- flake.nix
- nix/overlays/130-lib-hacknix.nix
This doesn't massively simplify the flake, but it helps a bit, and a few `hydraJobs` that used to not work, now do.
Note that this will break downstream users, because the flake's overlays and modules have changed structure. However, the fixes are trivial.
> refactor(nix)!: Switch to flake-parts.

- flake.nix
- nix/darwinModules/programs/git/default.nix
This enables us to use the common vault-agent github-credentials template on nix-darwin.
> feat: Add programs.git darwinModule (from nixpkgs NixOS module).

- nix/darwinModules/config/remote-builds/remote-build-host/default.nix
Signed-off-by: Drew Hess <src@drewhess.com>
> fix: use new nix-darwin OpenSSH key support for macOS users

- examples/nix-darwin/build-host.nix
- examples/nixos/build-host.nix
- nix/overlays/130-lib-hacknix.nix
- nix/overlays/131-lib-more-types.nix
This is helpful for using an SSH host key CA.
> chore: make remote builder SSH hostkeys optional

- .buildkite/cachix-push.yaml
We use the new Buildkite system.
Note that the macOS Nix shell push step is disabled until we've switched our Mac Buildkite agents to the new system.
> ci(buildkite): new Cachix push pipeline

- nix/common/config/services/vault/agent/template/cachix/default.nix
This is a breaking change.
Signed-off-by: Drew Hess <src@drewhess.com>
> !chore(vault-agent): render Cachix auth tokens rather than Dhall config

- examples/nixos/build-host.nix
- flake.nix
Turns out we no longer need to `import pkgs`; the flake's own packages are used by default. Just to be sure, we add one of our overlay's packages to the `build-host` image.
We also now build both LXC and qcow2 images, for completeness.
> fix: revive `nixosGenerators`

- nix/modules/services/vault/agent/default.nix
On our most recently-installed NixOS host, `vault-agent` mysteriously wouldn't start up, complaining about `$HOME` not being set. This hasn't been a problem before, but it's easy enough to fix.
> fix(vault-agent): set HOME env var in service config

- flake.nix
- nix/overlays/500-vector.nix
- nix/pkgs/vector/default.nix
For some reason, `vector` often breaks upstream on `aarch64-darwin`; e.g.:
https://hydra.nixos.org/build/285322715
However, upstream only seems to consider the `x86_64-linux` build for gating admission. We have downstreams that depend on `vector` on `aarch64-darwin`, so now we override it.
This initial commit is `v0.44.0`, which is about to enter upstream here:
https://github.com/NixOS/nixpkgs/pull/373601
Note that the upstream changes fail on `aarch64-darwin`. However, we were able to work around this simply by adding `zlib` to `buildInputs` on macOS. Maybe this is the long-term fix, though it's not clear why upstream hasn't already done this.
> chore: override `vector`

- flake.lock
- flake.nix
We should use the same `nixpkgs` across the board.
> chore(nix): override `nix-darwin` `nixpkgs` input

- nix/darwinModules/config/defaults/default.nix
It seems like most of the macOS sandbox issues have been resolved, except for the 64K sandbox program limit.
Here we enable the sandbox, but in order to work around this limit, we add `/nix/store` to the allowed paths by default. (Presumably the sandbox compiler is smart enough to replace multiple `/nix/store/...` paths with a single `/nix/store` parent path.)
This is less than optimal, but much safer than disabling the sandbox entirely, and probably safer than disabling the sandbox on a per-package, as-needed basis, as well.
Ref:
https://github.com/NixOS/nix/issues/4119#issuecomment-2561973914
Also see:
https://github.com/NixOS/nixpkgs/pull/346945
https://github.com/NixOS/nix/issues/6836
https://github.com/NixOS/nix/issues/4119
https://github.com/amarshall/home-manager/commit/d7319b754802 …
> chore(nix): enable the macOS sandbox, with caveats
